###

 Get http://127.0.0.1:8080/api/v1/info
 Content-Type: application/json

###

 Get http://127.0.0.1:8080/api/v1/health
 Content-Type: application/json

####
Post http://127.0.0.1:8080/api/v1/signup
Content-Type: application/json
# Authorization: Bearer eyJhbGc

{
    "email": "stc.5421@gmail.com",
    "name": "sadegh",
    "password": "123456"
}