###

 Get http://127.0.0.1:8080/api/v1/info
 Content-Type: application/json

###

 Get http://127.0.0.1:8080/api/v1/health
 Content-Type: application/json

####
Post http://127.0.0.1:8080/api/v1/login
Content-Type: application/json

####
Get http://127.0.0.1:8080/api/v1/token?refid=BsB2IuKsv1Wr5t31k6nRoQ
Content-Type: application/json


####
Get http://127.0.0.1:8080/api/v1/profile
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyMWRiZTM1MC00ZTFhLTQ4ZjktYTZjMC1iZGUzNjJlOTNiYWEiLCJuYW1lIjoiU2FkZWdoIiwiZW1haWwiOiIxMDMyNDk1NzU1NDg2NTg1MjA1ODkiLCJpYXQiOjE2ODk2NzMyNDUsImV4cCI6MTY5MDUzNzg0NX0.IGsFT_rpv-FTWotQqs1j1NWvxxvR5KIrbLJqYNXGQRY


####
Put http://127.0.0.1:8080/api/v1/profile
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyMWRiZTM1MC00ZTFhLTQ4ZjktYTZjMC1iZGUzNjJlOTNiYWEiLCJuYW1lIjoiU2FkZWdoIiwiZW1haWwiOiIxMDMyNDk1NzU1NDg2NTg1MjA1ODkiLCJpYXQiOjE2ODk2NzMyNDUsImV4cCI6MTY5MDUzNzg0NX0.IGsFT_rpv-FTWotQqs1j1NWvxxvR5KIrbLJqYNXGQRY

{
    "name": "Sadegh"
}
